# Generated by Django 5.1.4 on 2024-12-21 16:06

import django.db.models.deletion
import management_banque.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=13)),
                ('type_compte', models.CharField(max_length=30)),
                ('account_solde', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('account_status', models.CharField(default='actif', max_length=20)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=120)),
                ('civility', models.CharField(max_length=120)),
                ('agency', models.CharField(max_length=120)),
                ('birth_day', models.DateField()),
                ('nationality', models.CharField(choices=[('CD', 'République Démocratique du Congo (RDC)'), ('CG', 'République du Congo (Congo-Brazzaville)'), ('GA', 'Gabon'), ('CM', 'Cameroun'), ('TD', 'Tchad')], max_length=20, validators=[management_banque.models.central_country])),
                ('zip_code', models.CharField(max_length=10)),
                ('pin_code', models.CharField(max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
